export const TeamsEnum: Record<string, string> = {
  'NHL-ANA': 'Anaheim Ducks',
  'NFL-ARI': 'Arizona Cardinals',
  'MLB-ARI': 'Arizona Diamondbacks',
  'MLB-ATH': 'Athletics',
  'MLB-ATL': 'Atlanta Braves',
  'WNBA-ATL': 'Atlanta Dream',
  'NFL-ATL': 'Atlanta Falcons',
  'NBA-ATL': 'Atlanta Hawks',
  'MLS-ATL': 'Atlanta United Fc',
  'MLS-ATX': 'Austin Fc',
  'MLB-BAL': 'Baltimore Orioles',
  'NFL-BAL': 'Baltimore Ravens',
  'NHL-BOS': 'Boston Bruins',
  'NBA-BOS': 'Boston Celtics',
  'PWHL-BOS': 'Boston Fleet',
  'MLB-BOS': 'Boston Red Sox',
  'NBA-BKN': 'Brooklyn Nets',
  'NFL-BUF': 'Buffalo Bills',
  'NHL-BUF': 'Buffalo Sabres',
  'NHL-CGY': 'Calgary Flames',
  'NHL-CAR': 'Carolina Hurricanes',
  'NFL-CAR': 'Carolina Panthers',
  'MLS-MTL': 'Cf Montréal',
  'MLS-CLT': 'Charlotte Fc',
  'NBA-CHA': 'Charlotte Hornets',
  'NFL-CHI': 'Chicago Bears',
  'NHL-CHI': 'Chicago Blackhawks',
  'NBA-CHI': 'Chicago Bulls',
  'MLB-CHC': 'Chicago Cubs',
  'MLS-CHI': 'Chicago Fire Fc',
  'WNBA-CHI': 'Chicago Sky',
  'MLB-CHW': 'Chicago White Sox',
  'NFL-CIN': 'Cincinnati Bengals',
  'MLB-CIN': 'Cincinnati Reds',
  'NFL-CLE': 'Cleveland Browns',
  'NBA-CLE': 'Cleveland Cavaliers',
  'MLB-CLE': 'Cleveland Guardians',
  'NHL-COL': 'Colorado Avalanche',
  'MLS-COL': 'Colorado Rapids',
  'MLB-COL': 'Colorado Rockies',
  'NHL-CBJ': 'Columbus Blue Jackets',
  'MLS-CLB': 'Columbus Crew',
  'WNBA-CON': 'Connecticut Sun',
  'MLS-DC': 'D.c. United',
  'NFL-DAL': 'Dallas Cowboys',
  'NBA-DAL': 'Dallas Mavericks',
  'NHL-DAL': 'Dallas Stars',
  'WNBA-DAL': 'Dallas Wings',
  'NFL-DEN': 'Denver Broncos',
  'NBA-DEN': 'Denver Nuggets',
  'NFL-DET': 'Detroit Lions',
  'NBA-DET': 'Detroit Pistons',
  'NHL-DET': 'Detroit Red Wings',
  'MLB-DET': 'Detroit Tigers',
  'NHL-EDM': 'Edmonton Oilers',
  'MLS-CIN': 'Fc Cincinnati',
  'MLS-DAL': 'Fc Dallas',
  'NHL-FLA': 'Florida Panthers',
  'WNBA-GS': 'Golden State Valkyries',
  'NBA-GS': 'Golden State Warriors',
  'NFL-GB': 'Green Bay Packers',
  'MLB-HOU': 'Houston Astros',
  'MLS-HOU': 'Houston Dynamo Fc',
  'NBA-HOU': 'Houston Rockets',
  'NFL-HOU': 'Houston Texans',
  'WNBA-IND': 'Indiana Fever',
  'NBA-IND': 'Indiana Pacers',
  'NFL-IND': 'Indianapolis Colts',
  'MLS-MIA': 'Inter Miami Cf',
  'NFL-JAX': 'Jacksonville Jaguars',
  'NFL-KC': 'Kansas City Chiefs',
  'MLB-KC': 'Kansas City Royals',
  'NBA-LAC': 'La Clippers',
  'MLS-LA': 'La Galaxy',
  'MLS-LAFC': 'Lafc',
  'WNBA-LV': 'Las Vegas Aces',
  'NFL-LV': 'Las Vegas Raiders',
  'MLB-LAA': 'Los Angeles Angels',
  'NFL-LAC': 'Los Angeles Chargers',
  'MLB-LAD': 'Los Angeles Dodgers',
  'NHL-LA': 'Los Angeles Kings',
  'NBA-LAL': 'Los Angeles Lakers',
  'NFL-LAR': 'Los Angeles Rams',
  'WNBA-LA': 'Los Angeles Sparks',
  'NBA-MEM': 'Memphis Grizzlies',
  'NFL-MIA': 'Miami Dolphins',
  'NBA-MIA': 'Miami Heat',
  'MLB-MIA': 'Miami Marlins',
  'MLB-MIL': 'Milwaukee Brewers',
  'NBA-MIL': 'Milwaukee Bucks',
  'PWHL-MIN': 'Minnesota Frost',
  'WNBA-MIN': 'Minnesota Lynx',
  'NBA-MIN': 'Minnesota Timberwolves',
  'MLB-MIN': 'Minnesota Twins',
  'MLS-MIN': 'Minnesota United Fc',
  'NFL-MIN': 'Minnesota Vikings',
  'NHL-MIN': 'Minnesota Wild',
  'NHL-MTL': 'Montreal Canadiens',
  'PWHL-MTL': 'Montréal Victoire',
  'NHL-NSH': 'Nashville Predators',
  'MLS-NSH': 'Nashville Sc',
  'NFL-NE': 'New England Patriots',
  'MLS-NE': 'New England Revolution',
  'NHL-NJ': 'New Jersey Devils',
  'NBA-NO': 'New Orleans Pelicans',
  'NFL-NO': 'New Orleans Saints',
  'MLS-NYC': 'New York City Fc',
  'NFL-NYG': 'New York Giants',
  'NHL-NYI': 'New York Islanders',
  'NFL-NYJ': 'New York Jets',
  'NBA-NY': 'New York Knicks',
  'WNBA-NY': 'New York Liberty',
  'MLB-NYM': 'New York Mets',
  'NHL-NYR': 'New York Rangers',
  'MLS-NY': 'New York Red Bulls',
  'PWHL-NY': 'New York Sirens',
  'MLB-NYY': 'New York Yankees',
  'NBA-OKC': 'Oklahoma City Thunder',
  'MLS-ORL': 'Orlando City Sc',
  'NBA-ORL': 'Orlando Magic',
  'PWHL-OTT': 'Ottawa Charge',
  'NHL-OTT': 'Ottawa Senators',
  'NBA-PHI': 'Philadelphia 76ers',
  'NFL-PHI': 'Philadelphia Eagles',
  'NHL-PHI': 'Philadelphia Flyers',
  'MLB-PHI': 'Philadelphia Phillies',
  'MLS-PHI': 'Philadelphia Union',
  'WNBA-PHX': 'Phoenix Mercury',
  'NBA-PHX': 'Phoenix Suns',
  'NHL-PIT': 'Pittsburgh Penguins',
  'MLB-PIT': 'Pittsburgh Pirates',
  'NFL-PIT': 'Pittsburgh Steelers',
  'MLS-POR': 'Portland Timbers',
  'NBA-POR': 'Portland Trail Blazers',
  'MLS-RSL': 'Real Salt Lake',
  'NBA-SAC': 'Sacramento Kings',
  'NBA-SA': 'San Antonio Spurs',
  'MLS-SD': 'San Diego Fc',
  'MLB-SD': 'San Diego Padres',
  'NFL-SF': 'San Francisco 49ers',
  'MLB-SF': 'San Francisco Giants',
  'MLS-SJ': 'San Jose Earthquakes',
  'NHL-SJ': 'San Jose Sharks',
  'NHL-SEA': 'Seattle Kraken',
  'MLB-SEA': 'Seattle Mariners',
  'NFL-SEA': 'Seattle Seahawks',
  'MLS-SEA': 'Seattle Sounders Fc',
  'WNBA-SEA': 'Seattle Storm',
  'PWHL-SEA': 'Seattle Torrent',
  'MLS-SKC': 'Sporting Kansas City',
  'NHL-STL': 'St. Louis Blues',
  'MLB-STL': 'St. Louis Cardinals',
  'MLS-STL': 'St. Louis City Sc',
  'NFL-TB': 'Tampa Bay Buccaneers',
  'NHL-TB': 'Tampa Bay Lightning',
  'MLB-TB': 'Tampa Bay Rays',
  'NFL-TEN': 'Tennessee Titans',
  'MLB-TEX': 'Texas Rangers',
  'MLB-TOR': 'Toronto Blue Jays',
  'MLS-TOR': 'Toronto Fc',
  'NHL-TOR': 'Toronto Maple Leafs',
  'NBA-TOR': 'Toronto Raptors',
  'PWHL-TOR': 'Toronto Sceptres',
  'NBA-UTAH': 'Utah Jazz',
  'NHL-UTAH': 'Utah Mammoth',
  'NHL-VAN': 'Vancouver Canucks',
  'PWHL-VAN': 'Vancouver Goldeneyes',
  'MLS-VAN': 'Vancouver Whitecaps',
  'NHL-VGK': 'Vegas Golden Knights',
  'NHL-WSH': 'Washington Capitals',
  'NFL-WSH': 'Washington Commanders',
  'WNBA-WSH': 'Washington Mystics',
  'MLB-WSH': 'Washington Nationals',
  'NBA-WSH': 'Washington Wizards',
  'NHL-WPG': 'Winnipeg Jets',
};
